services:
  base: &base
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HTTP_SERVER_PORT=80
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PWD=postgres
      - DB_NAME=floor_finder
  floor_finder:
    <<: *base
    ports:
      - 8055:80
  
  unit_test:
    <<: *base
    build:
      context: .
      target: dev
    command: "go test"
    volumes:
      - .:/usr/local/src/floor_finder/
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PWD=postgres
      - DB_NAME=floor_finder_test
  
  db:
    image: postgis/postgis:14-3.2-alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54320:5432
    volumes:
      - ./init_dbs.sh:/docker-entrypoint-initdb.d/init_dbs.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
